---
name: CI/CD

"on": [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check the repository out
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test
        env:
          CI: true
      - name: Compile an optimized build
        run: yarn build --frozen-lockfile
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
        if: github.ref == 'refs/heads/master'
